services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on: [db]

  ocr:
    build:
      context: ./ocr
      dockerfile: Dockerfile

  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./models:/home/app/models
    depends_on: [db]

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    depends_on: [scraper]
    ports:
      - "5173:5173"
    
